spring:
  application:
    name: services-oride
  config:
    import:
      - optional:service-orider.properties
  cloud:
    nacos:
      username: nacos
      password: nacos
      config:
        server-addr: 192.168.38.1:8848
        username: ${spring.cloud.nacos.username}
        password: ${spring.cloud.nacos.password}
        file-extension: properties
        group: DEFAULT_GROUP
        refresh-enabled: true
        import-check:
          enabled: false
        access-key: ${spring.cloud.nacos.username}
        secret-key: ${spring.cloud.nacos.password}
      discovery:
        server-addr: 192.168.38.1:8848
        username: ${spring.cloud.nacos.username}
        password: ${spring.cloud.nacos.password}
        access-key: ${spring.cloud.nacos.username}
        secret-key: ${spring.cloud.nacos.password}
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 2000
          services-product1:
            loggerLevel: full
            connectTimeout: 3000
            readTimeout: 5000
  # 数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shopping?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis 配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#oride:
#  timeout: 300000
#  auto-confirm: 70

oride:
  timeout: default-30min
  auto-confirm: default-7d
#配置feign的日志级别
logging:
  level:
    org.example.Feign.GaoDefeign: DEBUG
    feign: DEBUG

server:
  port: 8004
